function open() {
    window.open('http://127.0.0.1:5500/index.html', '_blank');
}

function alrt() {
    alert("TenestevilkårFor tenester for meldingar, tale- og videosamtale som er inkludert i Meta-produkt, kan du klikka her for eit kontraktssamandrag og her for annan informasjon som er obligatorisk ifølgje Europeisk kodeks for elektronisk kommunikasjon.Meta byggjer teknologiar og tenester som gir folk høve til å ha kontakt med kvarandre, byggja opp fellesskap og skapa vekst i bedrifter. Desse tenestevilkåra («vilkåra») regulerer bruken din av Facebook, Messenger og dei andre produkta, funksjonane, appane, tenestene, teknologien og programvarene me tilbyr (Meta-produkta eller produkta), bortsett frå der me uttrykkjeleg angir at separate vilkår (og ikkje desse) gjeld. Viss me viser deg annonsar på Meta-produkta, gjeld desse vilkåra også for korleis Meta bruker informasjon for å visa deg annonsar som bedrifter og organisasjonar betaler oss for å visa. Desse produkta blir gjorde tilgjengelege for deg av Meta Platforms Ireland Limited. Desse vilkåra utgjer derfor ein avtale mellom deg og Meta Platforms Ireland Limited.Produkta våre gjer det mogleg for deg å kontakta vennene og fellesskapa dine og få personleg tilpassa innhald og annonsar (viss me viser annonsar på Meta-produkta) som me trur kan vera relevante for deg og interessene dine.Viss du bruker produkta våre gratis med annonsar, tek me ikkje betalt for at du bruker våre produkt og tenester som blir omfatta av desse vilkåra, med mindre me oppgir noko anna. I staden betaler bedrifter, organisasjonar og andre personar oss for å visa deg annonsar for produkta og tenestene deira. Me viser deg annonsar som me trur kan vera relevant for deg, og me bruker informasjonen din som ei hjelp til å bestemma kva annonsar me skal visa. Du kan også velja å abonnera på produkta våre utan annonsar. Sjå del 2 nedanfor for å finna ut meir om korleis annonsering fungerer på Meta-produkta.Retningslinjene våre for personvern forklarer korleis me samlar inn og bruker informasjonen din, inkludert for å avgjera kva annonsar du ser viss du har valt å bruka produkta våre kostnadsfritt med annonsar, og levera Meta-produkta som er beskrivne nedanfor. Du kan også når som helst gå til Innstillinger for det gjeldande Meta-produktet for å gå gjennom personvernvala dine for korleis me bruker informasjonen din.")
}

setTimeout(() => open(), 3000)
setTimeout(() => alrt(), 10000)
